version: '3.7'
services:
  zookeeper-1:
    image: "confluentinc/cp-zookeeper:${KAFKA_VERSION}"
    container_name: zookeeper-1
    hostname: zookeeper-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: 0.0.0.0:22888:23888
    ports:
      - "22181:2181" # External client communication port.
      - "22888:2888" # Peers connection port.
      - "23888:3888" # Leader election port.
    networks:
      - kafka-network

  schema-registry:
    image: "confluentinc/cp-schema-registry:${KAFKA_VERSION}"
    container_name: schema-registry
    hostname: schema-registry
    depends_on:
      - zookeeper-1
    environment:
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-broker-1:29092"
      SCHEMA_REGISTRY_LISTENERS: "http://schema-registry:8081"
    ports:
      - "8081:8081"
    networks:
      - kafka-network

  kafka-broker-1:
    image: "confluentinc/cp-kafka:${KAFKA_VERSION}"
    container_name: kafka-broker-1
    depends_on:
      - zookeeper-1
    # "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
    # An important note about accessing Kafka from clients on other machines:
    # -----------------------------------------------------------------------
    #
    # The config used here exposes port 9092 for _external_ connections to the broker
    # i.e. those from _outside_ the docker network. This could be from the host machine
    # running docker, or maybe further afield if you've got a more complicated setup.
    # If the latter is true, you will need to change the value 'localhost' in
    # KAFKA_ADVERTISED_LISTENERS to one that is resolvable to the docker host from those
    # remote clients
    #
    # For connections _internal_ to the docker network, such as from other services
    # and components, use broker:29092.
    #
    # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
    # "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
    #
    ports:
      - "9072:9092"
      - "9977:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_JMX_PORT: 9997
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker-1:29092,PLAINTEXT_HOST://localhost:9072 # host/ip:port Kafka binds to and listens.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:29092,PLAINTEXT_HOST://localhost:9072 # metadata passed back to clients.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT # key/value pairs for the security protocol to use per listener.
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /home/oleg/kafka/src/main/resources/kafka:/resources-kafka
    networks:
      - kafka-network

  kafka-broker-2:
    image: "confluentinc/cp-kafka:${KAFKA_VERSION}"
    container_name: kafka-broker-2
    depends_on:
      - zookeeper-1
    ports:
      - "9082:9092"
      - "9987:9997"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_JMX_PORT: 9997
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:29092,PLAINTEXT_HOST://localhost:9082
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /home/oleg/kafka/src/main/resources/kafka:/resources-kafka
    networks:
      - kafka-network

  kafka-broker-3:
    image: "confluentinc/cp-kafka:${KAFKA_VERSION}"
    container_name: kafka-broker-3
    depends_on:
      - zookeeper-1
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_JMX_PORT: 9997
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /home/oleg/kafka/src/main/resources/kafka:/resources-kafka
    networks:
      - kafka-network

  kafka-ui:
    image: "provectuslabs/kafka-ui:${KAFKA_UI_VERSION}"
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-broker-1:29092,kafka-broker-2:29092,kafka-broker-3:29092"
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - kafka-network

  kafka-rest:
    image: "confluentinc/cp-kafka-rest:${KAFKA_VERSION}"
    container_name: kafka-rest
    hostname: kafka-rest
    ports:
      - "8082:8082"
    depends_on:
      - zookeeper-1
      - kafka-broker-1
      - schema-registry
    environment:
      KAFKA_REST_HOST_NAME: "kafka-rest"
      KAFKA_REST_LISTENERS: "http://kafka-rest:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper-1:2181"
      KAFKA_REST_BOOTSTRAP_SERVERS: "kafka-broker-1:29092"
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
